language: go

go:
- 1.9.2

# services:
#   - rabbitmq

# env:
#   - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_install:
- go get -u -v github.com/golang/dep/...

install:
- $GOPATH/bin/dep ensure -v

script:
- go test -v ./...
